### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by souluu** [giltayar/babel-register-esm#2]
Does this actually work?

Errors with using import in ESM still

**Comment by giltayar** [comment]
It does. We use it at my company. A repro with some code would enable me to help you.

**Comment by giltayar** [comment]
Still no repro, so can't help a lot here. Did you notice: `Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension`?

**Comment by christian-bromann** [comment]
@giltayar I did some experiments and it seems that returning a transpiled source is ignored if the format is different from the current runtime. For example, given I am loading an ESM file that loads a CJS file (trough the import function) which has some imports that the user wants to see transpiled into cjs, the loader might does transformations on the CJS file but these will be ignored and the import fails due ` Cannot use import statement outside a module`.

Sounds confusing, I know.

My use case is with WebdriverIO v8 which runs in ESM. However if tests are written in CJS and I want to use Babel to use a mix of ESM and CJS, the transpiled code of the loader is being ignored. That said, this is not an issue of your loader package and more a Node.js thing.

**Comment by giltayar** [comment]
@christian-bromann can I close?
